/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nitins' at '11/13/16 8:10 PM' with Gradle 2.14.1
 *
 * @author nitins, @date 11/13/16 8:10 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
